### ISSUE TITLE
What is the library name?

### ISSUE THREAD

**Issue by GarryLai** [JohannesFriedrich/HypeRIMU#1]
What is the library name?
I used 

> library(HypeRIMU)

But it faild. It said find no package.

It seems that it install faild.
It said it cannot remove prior package 'backports'.

**Comment by JohannesFriedrich** [comment]
Hi!

Did you install the package with:

    if(!require("devtools"))
      install.packages("devtools")
      devtools::install_github("JohannesFriedrich/HypeRIMU")

Then the package ```HypeRIMU```should be found with ```library(HypeRIMU)```.
